### ISSUE TITLE
infinite loop for Z.div(Z(4), Z(-3))

### ISSUE THREAD

**Issue by Yaffle** [tabatkins/bignum#2]

**Comment by tabatkins** [comment]
Fixed, tho the divmod code is still messy as all hell and it's likely I'm doing something wrong for it in other cases.

(btw, thanks so much for the bug reports! you can tell which parts of the code i never actually called when doing Project Euler problems...)

**Comment by Yaffle** [comment]
@tabatkins , I just want to test your lib.
Seems, this still cause infinite loop for me: 
`Z.div(Z(4), Z(-3)).toString(10)`

Seems, `allowNegative` is not passed at `return Z.lift(a)._singleDigit();` - https://github.com/tabatkins/bignum/blob/master/Z.js#L574

**Comment by tabatkins** [comment]
Yeah, toString() code was exercising a different path that was still broken. Fixed as part of the bugfixing yesterday.
