### ISSUE TITLE
Z((-2)**25).toString(10) gives "--3-3-5-5-4-4-32"

### ISSUE THREAD

**Issue by Yaffle** [tabatkins/bignum#5]

**Comment by tabatkins** [comment]
Phew, *that* was an afternoon of poking at code to fix, as I had to make divmod() work properly for negative values, plus a bunch more.

Oh, and in the process I rewrote the thing to a newstyle class and a JS module, so if you're using it, you'll have to switch to module code.

**Comment by Yaffle** [comment]
@tabatkins , ooooh.... I didn't want you to make you you spending so much time on this.
I was just testing my test suite to see if it can find some bugs in your library . Today, we can use native `BigInt` in js.
Thanks.

**Comment by tabatkins** [comment]
hehe, it was helpful anyway, this is old code that I didn't do super great at, and fixing it is fun.
